services:
  database:
    image: postgres:latest
    container_name: knowbetter-db
    restart: always
    env_file:
      - .env
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: